# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
appVersion: 1.8.0
name: envoy-gateway-crds
description: Envoy Gateway CRDs
# URL of the GitHub repository that is the source of this Chart.yaml file.
home: https://github.com/giantswarm/envoy-gateway-crds-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
sources:
  - https://github.com/envoyproxy/gateway
version: 0.1.0
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.team: cabbage
