apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: gateway-helm
    helmChart:
      name: gateway-helm
      version: v1.8.0
      repository:
        url: oci://docker.io/envoyproxy
